### ISSUE TITLE
Rename repository and displayed text

### ISSUE THREAD

**Issue by Miklak93** [emarcins/drBartosiakQuotes#1]
At this moment the text displayed (and repository name) seems to be deprecated as https://x.com/ISPPAN/status/1801590437322301640
That's why I propose to change all "doktor" occurrences into "mgr".

**Comment by dwight1970** [comment]
@Miklak93 I believe a safer approach in this situation would be to go with "Mr".

**Comment by Miklak93** [comment]
@dwight1970 correct

**Comment by Skoczowianin** [comment]
@emarcins Please add me to the contributors, I prepared a commit to upgrade Dr to Mgr

Alternatively, you can review and apply below patch
[0001-Upgrade-from-Dr-to-Mgr.patch](https://github.com/user-attachments/files/15842577/0001-Upgrade-from-Dr-to-Mgr.patch)


Relevant class and variable names also updated

![obraz](https://github.com/emarcins/drBartosiakQuotes/assets/169139782/016f9557-a8b7-4eaa-97d3-b42446c4a9b5)

**Comment by emarcins** [comment]
> At this moment the text displayed (and repository name) seems to be deprecated as https://x.com/ISPPAN/status/1801590437322301640 That's why I propose to change all "doktor" occurrences into "mgr".

Done.

**Comment by Miklak93** [comment]
The issue resolved, thanks @emarcins. Ticket closed, the last remaining thing is to update "how it looks" photo example.
