### ISSUE TITLE
Typos and grammar errors

### ISSUE THREAD

**Issue by piotr-kwiatkowski** [emarcins/drBartosiakQuotes#2]
Typos:

- "Istotą jest asymetryczne wykorzystywanie przewagi na różnych szczeblach drabiny **_eksalacyjnej_**."
- "Szykowanie wojska następuje w kontekście wymiany kinetycznej z dominacją **_eksalacyjną_**."
- "Afgańczycy tak jak Wietnamczycy kiedyś, **_zdominiowali_** pętlę decyzyjną."
- "Ruch ludzi to klasyczny przepływ **_startegiczny_**."
- "**_Pradziwy_** system **_odpoproności_** państwa dotyczy manipulacji przepływami **_startegicznymi_**."
- "Kosmos będzie rozstrzygający w walce o przepływy **_staregiczne_** i panowanie na Ziemi ."

Grammar errors:

- "Nie da się przyjść z pomocą **_państwą_** bałtyckim bez poszerzenia podstawy operacyjnej." (państwom)
- "Rewizja doktryny **_Giedrojcia_** i Miroszewskiego jest potrzebna od zaraz." (Giedroycia)

Besides that - great project 💯😌

**Comment by emarcins** [comment]
It took a while but it's done! Thx. 🫡
